const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const env = require('./config/env');
const authRoutes = require('./routes/auth.routes');
const roleRoutes = require('./routes/role.routes');
const userRoutes = require('./routes/user.routes');
const leadRoutes = require('./routes/lead.routes');
const callRoutes = require('./routes/call.routes');
const fileUpdateRoutes = require('./routes/file-update.routes');
const sanctionRoutes = require('./routes/sanction.routes');
const pfUpdateRoutes = require('./routes/pf-update.routes');
const disbursementRoutes = require('./routes/disbursement.routes');
const crossSalesRoutes = require('./routes/cross-sales.routes');
const reportsRoutes = require('./routes/reports.routes');
const app = express();
const allowedOrigins = new Set([env.clientUrl, 'http://localhost:3000', 'http://127.0.0.1:3000']);
app.use(helmet());
app.use(cors({ origin(origin, callback) { if (!origin || allowedOrigins.has(origin)) return callback(null, true); return callback(new Error('Origin is not allowed by CORS')); } }));
app.use(express.json({ limit: '100kb' }));
if (env.nodeEnv !== 'test') app.use(morgan('dev'));
app.get('/api/v1/health', (_req,res) => res.json({ status:'ok' }));
app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/roles', roleRoutes);
app.use('/api/v1/users', userRoutes);
app.use('/api/v1/leads', leadRoutes);
app.use('/api/v1/calls', callRoutes);
app.use('/api/v1/file-updates', fileUpdateRoutes);
app.use('/api/v1/sanctions', sanctionRoutes);
app.use('/api/v1/pf-updates', pfUpdateRoutes);
app.use('/api/v1/disbursements', disbursementRoutes);
app.use('/api/v1/cross-sales', crossSalesRoutes);
app.use('/api/v1/reports', reportsRoutes);
app.use((_req,_res,next) => next(Object.assign(new Error('Route not found'), { statusCode: 404 })));
app.use((err,_req,res,_next) => { const status=err.statusCode || 500; if (status >= 500) console.error(err); res.status(status).json({ error: err.message || 'Internal server error' }); });
module.exports = app;
