import {useEffect,useState} from 'react';
import http from '../api/http';
import CallingManagementV2 from './CallingManagementV2';
import './calling-workflow-v6.css';
import './calling-workflow-v7.css';
import './calling-workflow-v8.css';

const statuses=['pending','connected','not_answered','interested','follow_up','not_interested','wrong_number','completed'];
export default function CallingWorkflowV8(){const [open,setOpen]=useState(false),[users,setUsers]=useState([]),[form,setForm]=useState({phone:'',status:'pending',assignedTo:'',notes:''}),[error,setError]=useState('');useEffect(()=>{http.get('/calls/meta').then(r=>setUsers(r.data.users)).catch(()=>{})},[]);const set=(key,value)=>setForm({...form,[key]:value});const save=async e=>{e.preventDefault();try{await http.post('/calls',form);setOpen(false);window.location.reload()}catch(x){setError(x.response?.data?.error||'Unable to add number')}};return <div className="single-number-workflow"><button className="single-number-button" onClick={()=>setOpen(true)}>+ Add single number</button><CallingManagementV2/>{open&&<div className="sn-overlay"><form className="sn-modal" onSubmit={save}><header><div><span>CALLING NUMBER</span><h2>Add single number</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></header>{error&&<p className="sn-error">{error}</p>}<label>Phone number *<input required value={form.phone} onChange={e=>set('phone',e.target.value)} placeholder="Enter phone number"/></label><label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}>{statuses.map(status=><option key={status} value={status}>{status.replaceAll('_',' ')}</option>)}</select></label><label>Assign to<select value={form.assignedTo} onChange={e=>set('assignedTo',e.target.value)}><option value="">Unassigned</option>{users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label>Call note<textarea rows="4" value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="Optional note"/></label><footer><button type="button" className="c2secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="c2primary">Save number</button></footer></form></div>}</div>}
