import {useCallback,useEffect,useState} from 'react';
import http from '../api/http';
import {useAuth} from '../auth/AuthContext';
import './calls.css';
const statuses=['pending','connected','not_answered','interested','follow_up','not_interested','wrong_number','completed'];
const empty={leadId:'',customerName:'',phone:'',status:'pending',notes:'',followUpAt:'',assignedTo:'',markCalled:false};
const label=x=>String(x||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const asForm=x=>({leadId:x.lead_id||'',customerName:x.customer_name||'',phone:x.phone||'',status:x.status||'pending',notes:x.notes||'',followUpAt:x.follow_up_at?x.follow_up_at.slice(0,16):'',assignedTo:x.assigned_to||'',markCalled:false});
export default function CallingManagement(){const {user}=useAuth(),canManage=user.permissions.includes('calling.manage');const [calls,setCalls]=useState([]),[meta,setMeta]=useState({users:[],leads:[]}),[stats,setStats]=useState({}),[filter,setFilter]=useState({search:'',status:'',page:1}),[page,setPage]=useState({page:1,pages:1,total:0}),[modal,setModal]=useState(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams({page:String(filter.page),limit:'10'});if(filter.search)q.set('search',filter.search);if(filter.status)q.set('status',filter.status);const [list,info,counts]=await Promise.all([http.get(`/calls?${q}`),http.get('/calls/meta'),http.get('/calls/stats')]);setCalls(list.data.calls);setPage(list.data.pagination);setMeta(info.data);setStats(counts.data);}catch(err){setNotice(err.response?.data?.error||'Unable to load calls')}finally{setLoading(false)}},[filter]);useEffect(()=>{load()},[load]);
const setF=(key,value)=>setFilter(old=>({...old,[key]:value,page:key==='page'?value:1}));const save=async e=>{e.preventDefault();try{if(modal.id)await http.patch(`/calls/${modal.id}`,modal.data);else await http.post('/calls',modal.data);setModal(null);load()}catch(err){setNotice(err.response?.data?.error||'Unable to save call')}};const remove=async item=>{if(!confirm(`Delete call for ${item.customer_name}?`))return;try{await http.delete(`/calls/${item.id}`);load()}catch(err){setNotice(err.response?.data?.error||'Unable to delete call')}};
return <section className="page calls-page"><div className="call-head"><div><span>CALL CENTER</span><h1>Call management</h1><p>Prioritize leads, record outcomes and never miss a follow-up.</p></div>{canManage&&<button className="call-primary" onClick={()=>setModal({id:null,data:empty})}>+ Schedule call</button>}</div>{notice&&<div className="call-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<div className="call-stats"><Stat icon="◌" title="Total calls" value={stats.total||0}/><Stat icon="◷" title="Pending" value={stats.pending||0}/><Stat icon="↻" title="Follow ups" value={stats.followUps||0}/><Stat icon="✓" title="Completed" value={stats.completed||0}/></div><div className="call-filters"><label>⌕<input value={filter.search} placeholder="Search customer, phone or lead" onChange={e=>setF('search',e.target.value)}/></label><select value={filter.status} onChange={e=>setF('status',e.target.value)}><option value="">All statuses</option>{statuses.map(x=><option key={x}>{label(x)}</option>)}</select><button onClick={()=>setFilter({search:'',status:'',page:1})}>Clear</button></div><div className="call-table"><table><thead><tr><th>S.NO</th><th>CUSTOMER</th><th>PHONE</th><th>LEAD</th><th>STATUS</th><th>FOLLOW UP</th><th>CALLS</th><th>ASSIGNED TO</th>{canManage&&<th>ACTION</th>}</tr></thead><tbody>{loading?<tr><td colSpan="9" className="call-empty">Loading calls...</td></tr>:calls.map((item,index)=><tr key={item.id}><td className="call-no">{(page.page-1)*10+index+1}</td><td><b>{item.customer_name}</b><small>{item.notes||'No notes added'}</small></td><td><a href={`tel:${item.phone}`}>{item.phone}</a></td><td>{item.lead_name||'—'}</td><td><span className={`call-pill st-${item.status}`}>{label(item.status)}</span></td><td>{item.follow_up_at?new Date(item.follow_up_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'}</td><td>{item.call_count}</td><td>{item.assigned_to_name||<i>Unassigned</i>}</td>{canManage&&<td><div className="call-actions"><button title="Log call" onClick={()=>setModal({id:item.id,data:{...asForm(item),markCalled:true}})}><Phone/></button><button title="Edit call" onClick={()=>setModal({id:item.id,data:asForm(item)})}><Edit/></button><button title="Delete call" onClick={()=>remove(item)}><Trash/></button></div></td>}</tr>)}{!loading&&!calls.length&&<tr><td colSpan="9" className="call-empty">No calls found.</td></tr>}</tbody></table></div><div className="call-pager"><button disabled={page.page<=1} onClick={()=>setF('page',page.page-1)}>← Previous</button><span>{page.page} / {page.pages}</span><button disabled={page.page>=page.pages} onClick={()=>setF('page',page.page+1)}>Next →</button></div>{modal&&<CallForm modal={modal} setModal={setModal} meta={meta} save={save}/>}</section>}
function Stat({icon,title,value}){return <article><span>{icon}</span><div><small>{title}</small><b>{value}</b></div></article>}
function CallForm({modal,setModal,meta,save}){const data=modal.data,set=(key,value)=>setModal({...modal,data:{...data,[key]:value}}),chooseLead=id=>{const lead=meta.leads.find(x=>x.id===Number(id));setModal({...modal,data:{...data,leadId:id,customerName:lead?.name||data.customerName,phone:lead?.phone||data.phone}})};return <div className="call-overlay"><form className="call-dialog" onSubmit={save}><div className="call-modal-head"><div><span>{modal.id?'UPDATE CALL':'NEW CALL'}</span><h2>{modal.id?'Log call outcome':'Schedule a call'}</h2></div><button type="button" onClick={()=>setModal(null)}>×</button></div><div className="call-form-grid"><label>Link lead<select value={data.leadId} onChange={e=>chooseLead(e.target.value)}><option value="">No linked lead</option>{meta.leads.map(x=><option key={x.id} value={x.id}>{x.name} · {x.phone}</option>)}</select></label><label>Customer name *<input value={data.customerName} onChange={e=>set('customerName',e.target.value)} required/></label><label>Phone number *<input value={data.phone} onChange={e=>set('phone',e.target.value)} required/></label><label>Assigned to<select value={data.assignedTo} onChange={e=>set('assignedTo',e.target.value)}><option value="">Unassigned</option>{meta.users.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Status<select value={data.status} onChange={e=>set('status',e.target.value)}>{statuses.map(x=><option key={x}>{label(x)}</option>)}</select></label><label>Follow-up date & time<input type="datetime-local" value={data.followUpAt} onChange={e=>set('followUpAt',e.target.value)}/></label><label className="call-wide">Call notes<textarea rows="4" value={data.notes} onChange={e=>set('notes',e.target.value)} placeholder="What happened during the call?"/></label>{modal.id&&<label className="mark-called"><input type="checkbox" checked={data.markCalled} onChange={e=>set('markCalled',e.target.checked)}/> Mark this call as completed now</label>}</div><div className="call-modal-footer"><button type="button" className="call-secondary" onClick={()=>setModal(null)}>Cancel</button><button className="call-primary">{modal.id?'Save call log':'Schedule call'}</button></div></form></div>}
function Phone(){return <svg viewBox="0 0 24 24"><path d="M5 3h4l2 5-2.5 1.5a15 15 0 0 0 6 6L16 13l5 2v4c0 1-1 2-2 2C10 21 3 14 3 5c0-1 1-2 2-2Z"/></svg>}function Edit(){return <svg viewBox="0 0 24 24"><path d="M4 20h4l10-10-4-4L4 16v4Z"/><path d="m12.5 7.5 4 4"/></svg>}function Trash(){return <svg viewBox="0 0 24 24"><path d="M4 7h16M10 11v5m4-5v5M9 7l1-2h4l1 2m-9 0 1 13h10l1-13"/></svg>}
