import { useCallback, useEffect, useState } from 'react';
import http from '../api/http';
import { useAuth } from '../auth/AuthContext';
import './leads-v2.css';

const statuses=['new','interested','file_update','login','sanction','pf_paid','disbursed','rejected'];
const blank={name:'',phone:'',email:'',country:'',university:'',loanAmount:'',studentName:'',coApplicant:'',occupation:'',source:'Direct',remarks:'',loginCity:'',sanctionCity:'',creditScore:'',status:'new',assignedTo:''};
const fields={name:'name',lead_name:'name',phone:'phone',mobile:'phone',number:'phone',email:'email',country:'country',university:'university',loan_amount:'loanAmount',student_name:'studentName',co_applicant:'coApplicant',occupation:'occupation',source:'source',remarks:'remarks',login_city:'loginCity',sanction_city:'sanctionCity',credit_score:'creditScore',status:'status',assigned_to:'assignedTo'};
const title=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const toMoney=value=>Number(value||0).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
const toForm=lead=>({name:lead.name||'',phone:lead.phone||'',email:lead.email||'',country:lead.country||'',university:lead.university||'',loanAmount:lead.loan_amount||'',studentName:lead.student_name||'',coApplicant:lead.co_applicant||'',occupation:lead.occupation||'',source:lead.source||'Direct',remarks:lead.remarks||'',loginCity:lead.login_city||'',sanctionCity:lead.sanction_city||'',creditScore:lead.credit_score||'',status:lead.status||'new',assignedTo:lead.assigned_to||''});
function csvRows(text){const result=[];let r=[],v='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){v+='"';i++;}else if(c==='"')q=!q;else if(c===','&&!q){r.push(v.trim());v='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;r.push(v.trim());if(r.some(x=>x))result.push(r);r=[];v='';}else v+=c;}r.push(v.trim());if(r.some(x=>x))result.push(r);return result;}

export default function LeadManagementV2(){
 const {user}=useAuth(),canManage=user.permissions.includes('leads.manage'); const [rows,setRows]=useState([]),[meta,setMeta]=useState({sources:[],users:[]}),[filter,setFilter]=useState({search:'',status:'',source:'',page:1}),[page,setPage]=useState({page:1,pages:1,total:0}),[lead,setLead]=useState(null),[editing,setEditing]=useState(false),[bulk,setBulk]=useState(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const p=new URLSearchParams({page:String(filter.page),limit:'10'});for(const key of ['search','status','source'])if(filter[key])p.set(key,filter[key]);const [list,info]=await Promise.all([http.get(`/leads?${p}`),http.get('/leads/meta')]);setRows(list.data.leads);setPage(list.data.pagination);setMeta(info.data);}catch(e){setMessage(e.response?.data?.error||'Unable to load leads');}finally{setLoading(false);}},[filter]); useEffect(()=>{load();},[load]);
 const setF=(key,value)=>setFilter(old=>({...old,[key]:value,page:key==='page'?value:1}));
 const save=async e=>{e.preventDefault();try{if(editing)await http.patch(`/leads/${editing}`,lead);else await http.post('/leads',lead);setLead(null);load();}catch(err){setMessage(err.response?.data?.error||'Unable to save lead');}};
 const remove=async item=>{if(!confirm(`Delete ${item.name}?`))return;try{await http.delete(`/leads/${item.id}`);load();}catch(err){setMessage(err.response?.data?.error||'Unable to delete lead');}};
 const template=()=>{const data='name,phone,email,country,university,loan_amount,student_name,co_applicant,occupation,source,remarks,login_city,sanction_city,credit_score,status,assigned_to\nAarav Sharma,9876543210,aarav@example.com,Canada,York University,3200000,Aarav Sharma,Rakesh Sharma,Student,Website,Requested eligibility,Delhi,,745,interested,';const url=URL.createObjectURL(new Blob([data],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='lead-upload-template.csv';a.click();URL.revokeObjectURL(url);};
 const choose=async e=>{const file=e.target.files?.[0];if(!file)return;const data=csvRows(await file.text());const heads=(data.shift()||[]).map(x=>fields[x.toLowerCase().trim().replaceAll(' ','_')]||'');setBulk({file:file.name,items:data.map(row=>Object.fromEntries(row.map((value,i)=>[heads[i],value]).filter(([key])=>key))),result:null});e.target.value='';};
 const importCsv=async()=>{try{const result=await http.post('/leads/bulk',{leads:bulk.items});setBulk(old=>({...old,result:result.data}));load();}catch(err){setMessage(err.response?.data?.error||'Bulk upload failed');}};
 return <section className="page leads2"><div className="lead2-head"><div><span>CRM PIPELINE</span><h1>Lead management</h1><p>Collect, qualify and manage every student loan lead.</p></div>{canManage&&<div className="lead2-actions"><button className="ghost" onClick={template}>Download CSV template</button><label className="ghost">Bulk upload<input type="file" accept=".csv,text/csv" onChange={choose}/></label><button className="primary" onClick={()=>{setLead(blank);setEditing(false);setMessage('');}}>+ Add new lead</button></div>}</div>{message&&<div className="notice">{message}</div>}<div className="filters"><label>⌕<input placeholder="Search name, phone, email or university" value={filter.search} onChange={e=>setF('search',e.target.value)}/></label><select value={filter.status} onChange={e=>setF('status',e.target.value)}><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select value={filter.source} onChange={e=>setF('source',e.target.value)}><option value="">All sources</option>{meta.sources.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setFilter({search:'',status:'',source:'',page:1})}>Clear</button></div><div className="count"><span><b>{page.total}</b> leads found</span><span>Page {page.page} of {page.pages}</span></div><div className="lead2-table"><table><thead><tr><th>LEAD</th><th>CONTACT</th><th>STUDY DESTINATION</th><th>LOAN AMOUNT</th><th>SOURCE</th><th>STATUS</th><th>ASSIGNED TO</th>{canManage&&<th>ACTION</th>}</tr></thead><tbody>{loading?<tr><td colSpan="8" className="blank">Loading leads...</td></tr>:rows.map(item=><tr key={item.id}><td><b>{item.name}</b><small>{item.student_name||'Student'}</small></td><td>{item.phone}<small>{item.email||'No email'}</small></td><td><b>{item.country||'—'}</b><small>{item.university||'University not added'}</small></td><td>{toMoney(item.loan_amount)}</td><td><em>{item.source}</em></td><td><span className={`lead-pill status-${item.status}`}>{title(item.status)}</span></td><td>{item.assigned_to_name||<i>Unassigned</i>}</td>{canManage&&<td className="row-actions"><button onClick={()=>{setLead(toForm(item));setEditing(item.id);}}>Edit</button><button onClick={()=>remove(item)}>Delete</button></td>}</tr>)}{!loading&&!rows.length&&<tr><td colSpan="8" className="blank">No leads match these filters.</td></tr>}</tbody></table></div><div className="pager"><button disabled={page.page<=1} onClick={()=>setF('page',page.page-1)}>← Previous</button><span>{page.page} / {page.pages}</span><button disabled={page.page>=page.pages} onClick={()=>setF('page',page.page+1)}>Next →</button></div>{lead&&<LeadForm value={lead} setValue={setLead} meta={meta} edit={editing} save={save} close={()=>setLead(null)}/>} {bulk&&<BulkDialog bulk={bulk} close={()=>setBulk(null)} run={importCsv}/>}</section>;
}
function LeadForm({value,setValue,meta,edit,save,close}){const field=(key,label,type='text')=><label>{label}<input type={type} value={value[key]} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>;return <div className="shade"><form className="lead-dialog" onSubmit={save}><header><div><span>{edit?'UPDATE LEAD':'NEW LEAD'}</span><h2>{edit?'Edit lead details':'Create new lead'}</h2></div><button type="button" onClick={close}>×</button></header><div className="form-grid"><label>Lead name *<input value={value.name} onChange={e=>setValue({...value,name:e.target.value})} required/></label><label>Phone number *<input value={value.phone} onChange={e=>setValue({...value,phone:e.target.value})} required/></label>{field('email','Email','email')}{field('studentName','Student name')}{field('country','Country')}{field('university','University')}{field('loanAmount','Loan amount','number')}{field('creditScore','Credit score','number')}{field('coApplicant','Co-applicant')}{field('occupation','Occupation')}{field('source','Source')}<label>Status<select value={value.status} onChange={e=>setValue({...value,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label>{field('loginCity','Login city')}{field('sanctionCity','Sanction city')}<label>Assign to<select value={value.assignedTo} onChange={e=>setValue({...value,assignedTo:e.target.value})}><option value="">Unassigned</option>{meta.users.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="wide">Remarks<textarea rows="3" value={value.remarks} onChange={e=>setValue({...value,remarks:e.target.value})}/></label></div><footer><button type="button" className="ghost" onClick={close}>Cancel</button><button className="primary">{edit?'Save changes':'Create lead'}</button></footer></form></div>}
function BulkDialog({bulk,close,run}){return <div className="shade"><div className="bulk-dialog"><header><div><span>CSV BULK UPLOAD</span><h2>Import leads</h2></div><button onClick={close}>×</button></header>{bulk.result?<><div className="result"><b>{bulk.result.imported} leads imported</b><span>{bulk.result.skipped} skipped</span></div>{bulk.result.errors.slice(0,5).map(x=><p key={x.row}>Row {x.row}: {x.message}</p>)}<footer><button className="primary" onClick={close}>Done</button></footer></>:<><p><b>{bulk.file}</b> contains <b>{bulk.items.length}</b> data rows.</p><div className="preview">{bulk.items.slice(0,3).map((x,i)=><div key={i}><b>{x.name||'Missing name'}</b><small>{x.phone||'Missing phone'} · {x.status||'new'}</small></div>)}</div><footer><button className="ghost" onClick={close}>Cancel</button><button className="primary" onClick={run}>Import {bulk.items.length} leads</button></footer></>}</div></div>}
