import { useEffect, useState } from 'react';
import http from '../api/http';
import { useAuth } from '../auth/AuthContext';
import './rbac.css';

const blank = { name: '', permissionIds: [] };
export default function RoleManagement() {
  const { user } = useAuth();
  const [roles, setRoles] = useState([]); const [permissions, setPermissions] = useState([]); const [editing, setEditing] = useState(null); const [form, setForm] = useState(blank); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [roleRes, permissionRes] = await Promise.all([http.get('/roles'), http.get('/roles/permissions')]); setRoles(roleRes.data.roles); setPermissions(permissionRes.data.permissions); } catch (err) { setError(err.response?.data?.error || 'Unable to load role data'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const open = role => { setError(''); setEditing(role || {}); setForm(role ? { name: role.name, permissionIds: role.permissions.map(p => p.id) } : blank); };
  const save = async event => { event.preventDefault(); try { if (editing.id) await http.patch(`/roles/${editing.id}`, form); else await http.post('/roles', form); setEditing(null); load(); } catch (err) { setError(err.response?.data?.error || 'Unable to save role'); } };
  const remove = async role => { if (!confirm(`Delete ${role.name}?`)) return; try { await http.delete(`/roles/${role.id}`); load(); } catch (err) { setError(err.response?.data?.error || 'Unable to delete role'); } };
  const toggle = id => setForm(current => ({ ...current, permissionIds: current.permissionIds.includes(id) ? current.permissionIds.filter(item => item !== id) : [...current.permissionIds, id] }));
  if (user.roleKey !== 'super_admin') return <section className="page"><h1>Access denied</h1><p>Only Super Admin can manage roles and permissions.</p></section>;
  return <section className="page rbac-page"><div className="page-title"><div><span className="eyebrow">ACCESS CONTROL</span><h1>Roles & permissions</h1><p>Create roles and decide exactly what each team can access.</p></div><button className="violet-button" onClick={() => open(null)}>+ Create role</button></div>{error && <div className="alert">{error}</div>}{loading ? <div className="empty-box">Loading access controls...</div> : <div className="role-grid">{roles.map(role => <article className="role-card" key={role.id}><div className="role-card-head"><div><span className={role.key === 'super_admin' ? 'role-badge super' : 'role-badge'}>{role.key === 'super_admin' ? 'SUPER ADMIN' : 'ROLE'}</span><h2>{role.name}</h2></div><span className="user-count">{role.userCount} user{role.userCount !== 1 ? 's' : ''}</span></div><p className="permission-count">{role.key === 'super_admin' ? 'All permissions are permanently enabled.' : `${role.permissions.length} permission${role.permissions.length !== 1 ? 's' : ''} enabled`}</p><div className="permission-pills">{role.permissions.slice(0, 4).map(permission => <span key={permission.id}>{permission.key}</span>)}{role.permissions.length > 4 && <span>+{role.permissions.length - 4} more</span>}</div><div className="role-actions">{role.key === 'super_admin' ? <span className="locked-note">Locked system role</span> : <><button onClick={() => open(role)}>Edit access</button><button className="danger-link" onClick={() => remove(role)}>Delete</button></>}</div></article>)}</div>}{editing && <div className="modal-backdrop"><form className="rbac-modal" onSubmit={save}><div className="modal-header"><div><span className="eyebrow">ROLE SETTINGS</span><h2>{editing.id ? `Edit ${editing.name}` : 'Create a role'}</h2></div><button type="button" className="close-button" onClick={() => setEditing(null)}>×</button></div><label className="field-label">Role name<input value={form.name} placeholder="e.g. Telecaller" onChange={e => setForm({ ...form, name: e.target.value })} required /></label><div className="permission-heading"><b>Permissions</b><button type="button" onClick={() => setForm({ ...form, permissionIds: permissions.map(p => p.id) })}>Select all</button></div><div className="permission-checklist">{permissions.map(permission => <label key={permission.id}><input type="checkbox" checked={form.permissionIds.includes(permission.id)} onChange={() => toggle(permission.id)} /><span><b>{permission.name}</b><small>{permission.key}</small></span></label>)}</div>{error && <div className="alert">{error}</div>}<div className="modal-actions"><button type="button" className="cancel-button" onClick={() => setEditing(null)}>Cancel</button><button className="violet-button">{editing.id ? 'Save changes' : 'Create role'}</button></div></form></div>}</section>;
}
