import { useEffect, useState } from 'react';
import http from '../api/http';
import { useAuth } from '../auth/AuthContext';
import './rbac.css';

const emptyForm = { name: '', email: '', password: '', roleId: '' };
export default function UserManagement() {
  const { user: currentUser } = useAuth(); const [users, setUsers] = useState([]); const [roles, setRoles] = useState([]); const [form, setForm] = useState(null); const [error, setError] = useState('');
  const load = async () => { try { const [userRes, roleRes] = await Promise.all([http.get('/users'), http.get('/roles')]); setUsers(userRes.data.users); setRoles(roleRes.data.roles); } catch (err) { setError(err.response?.data?.error || 'Unable to load users'); } };
  useEffect(() => { load(); }, []);
  const save = async event => { event.preventDefault(); try { const payload = { ...form, roleId: Number(form.roleId) }; if (!payload.password) delete payload.password; if (form.id) await http.patch(`/users/${form.id}`, payload); else await http.post('/users', payload); setForm(null); load(); } catch (err) { setError(err.response?.data?.error || 'Unable to save user'); } };
  const remove = async user => { if (!confirm(`Delete ${user.name}?`)) return; try { await http.delete(`/users/${user.id}`); load(); } catch (err) { setError(err.response?.data?.error || 'Unable to delete user'); } };
  if (currentUser.roleKey !== 'super_admin') return <section className="page"><h1>Access denied</h1></section>;
  return <section className="page rbac-page"><div className="page-title"><div><span className="eyebrow">TEAM ACCESS</span><h1>Users</h1><p>Assign each teammate the correct role and access level.</p></div><button className="violet-button" onClick={() => { setError(''); setForm(emptyForm); }}>+ Add user</button></div>{error && <div className="alert">{error}</div>}<div className="user-table-wrap"><table className="user-table"><thead><tr><th>USER</th><th>EMAIL</th><th>ROLE</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><b>{user.name}</b>{user.id === currentUser.id && <small> You</small>}</td><td>{user.email}</td><td><span className="table-role">{user.role}</span></td><td><span className={user.is_active ? 'active-status' : 'inactive-status'}>{user.is_active ? 'Active' : 'Inactive'}</span></td><td><button className="table-action" onClick={() => { setError(''); setForm({ id: user.id, name: user.name, email: user.email, password: '', roleId: String(user.role_id), isActive: Boolean(user.is_active) }); }}>Edit</button>{user.id !== currentUser.id && <button className="table-delete" onClick={() => remove(user)}>Delete</button>}</td></tr>)}</tbody></table></div>{form && <div className="modal-backdrop"><form className="rbac-modal" onSubmit={save}><div className="modal-header"><div><span className="eyebrow">TEAM MEMBER</span><h2>{form.id ? 'Edit user' : 'Add user'}</h2></div><button type="button" className="close-button" onClick={() => setForm(null)}>×</button></div><label className="field-label">Full name<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /></label><label className="field-label">Email<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /></label><label className="field-label">{form.id ? 'New password (leave blank to keep it)' : 'Password'}<input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} required={!form.id} /></label><label className="field-label">Role<select value={form.roleId} onChange={e => setForm({ ...form, roleId: e.target.value })} required><option value="">Select role</option>{roles.map(role => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label>{form.id && <label className="toggle-row"><input type="checkbox" checked={form.isActive} onChange={e => setForm({ ...form, isActive: e.target.checked })} /> Account active</label>}<div className="modal-actions"><button type="button" className="cancel-button" onClick={() => setForm(null)}>Cancel</button><button className="violet-button">Save user</button></div></form></div>}</section>;
}
